# docker-compose.yaml
services:
  lasertainer:
    container_name: LaserTainer
    image:  kirkbya/brightlife-device:latest
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
    - SERIAL_NO=LT-1
    network_mode: "host"

  feeder:
    container_name: Feeder
    image:  kirkbya/brightlife-device:latest
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
    - SERIAL_NO=FE-1
    network_mode: "host"