version: '2.1'

volumes:
  localtime:

services:
  # balena-starter-interface:
  #   image: ghcr.io/balena-labs-research/bsi-pwc-block:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #   labels:
  #     io.balena.features.supervisor-api: 1
  #     io.balena.features.balena-api: 1

  # python-wifi-connect:
  #   image: ghcr.io/balena-labs-research/python-wifi-connect:latest
  #   environment:
  #     # Hotspot details
  #     PWC_HOTSPOT_SSID: "Python WiFi Connect" # Name as it appears in list of WiFi networks
  #     # PWC_HOTSPOT_PASSWORD: "balena01" # Optional. Must be 8 characters or more

  #     # Required system variables
  #     DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  #   network_mode: "host"
  #   restart: always
  #   volumes:
  #     - "pwc_db:/app/db" # Optional if not setting the hotspot SSID and password via the API
  #   labels:
  #     io.balena.features.dbus: "1"
  #   cap_add:
  #     - NET_ADMIN
  #   privileged: true # This can be removed if you do not need the LED connectivity indicator.

  # wifi-connect:
  #   image: bh.cr/balenalabs/wifi-connect-rpi
  #   restart: always
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: "1"
  #     io.balena.features.firmware: "1"
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #       DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"

  # python-wifi-connect:
  #   environment:
  #     ## Listening IP and port ##
  #     PWC_HOST: "0.0.0.0"
  #     PWC_PORT: 9090

  #     ## Hotspot details ##
  #     PWC_HOTSPOT_SSID: "Python Wi-Fi Connect"
  #     #PWC_HOTSPOT_PASSWORD: "my-hotspot-password" # Optional. Must be 8 characters or more.

  #     ## Try to automatically connect to a Wi-Fi network on first boot ##
  #     #PWC_AC_SSID: "network-name" # Compulsory for this feature
  #     #PWC_AC_USERNAME: "username" # Optional
  #     #PWC_AC_PASSWORD: "your-password" # Optional. Must be 8 characters or more.

  #     ## Wi-Fi Interface ##
  #     #PWC_INTERFACE: "wlan0" # By default it automatically detects the interface.

  #     ## Enable/Disable LED interaction ##
  #     #PWC_LED: "on"

  #     ## Required system variables ##
  #     DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  #   image: bh.cr/maggie0002/python-wifi-connect
  #   network_mode: "host"
  #   restart: on-failure
  #   volumes:
  #     - "py_wifi_connect_db:/app/db" # Optional if not setting the hotspot ssid and password via the API
  #   labels:
  #     io.balena.features.dbus: "1"
  #   cap_add:
  #     - NET_ADMIN
  #   privileged: true # This can be removed if you do not need the LED indicator.

  system:
    container_name: System
    privileged: true
    build:  ./
    cap_add:
      - NET_ADMIN
    volumes:
      - localtime:/etc/localtime
    network_mode: "host"
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"